' Scenario      : FSL.DiagramTest.Quiet
' Instance pid  : #PID<0.578.0>
' Configuration (passwords masked):
'
@startuml
participant local
participant peer

note over local : initial_state
note over local #LightGreen : succeeded: done
@enduml
